name: 'Get Dependent Pull Request'
description: 'This checks current PR body for a dependent PR'
author: 'Sentry'
inputs:
  appId:
    required: true
    description: GitHub App ID
  privateKey:
    required: true
    description: GitHub App private key
  textPattern:
    required: false
    description: The regex pattern to use against the referencer, note this is passed to RegExp()
  patternFlags:
    required: false
    description: The regex flags to use for `textPattern`
  repo:
    required: false
    description: The exact owner/repo to match to
outputs:
  sha:
    description: The HEAD SHA for the dependent pull request
  branch:
    description: The branch of the pull request
  number:
    description: The pull request number
  pullRequest:
    description: Stringified pull request object
runs:
  using: 'node12'
  main: 'dist/index.js'
